### ISSUE TITLE
Bug NametagEdit + MultiverseCore

### ISSUE THREAD

**Issue by xELITESx** [sgtcaze/NametagEdit#223]
# Bug Report

Hi, this bug happend  using NametagEdit (i use last version of jenkins) + MultiverseCore (last version):
Exemple:
my ranks are: **Owner**, **Admin** and **Mod** (_Owner most important_).
Bug: if you make you player on Admin  rank, (using multiverse on same server), tab will said that you are Owner rank, but if you write on chat (using permissionsEx), chat said you are Admin.
i think my english is not good, so i will give you a YouTube video to show this, (only you can see this video): https://www.youtube.com/watch?v=vcEC9pg7x1U&feature=youtu.be

**Comment by sgtcaze** [comment]
It sounds like you may have different per-world permissions. NametagEdit normally should work fine with multiple worlds (using Multiverse) -- so it's likely users have different permissions in these worlds, which is overriding the default sort order. That's the first thing that comes to mind.

**Comment by xELITESx** [comment]
so, what can i do to fix it?

**Comment by sgtcaze** [comment]
Please post your **groups.yml** file. I think this is a "GroupOrder" issue.

Edit: please also post your multiverse world permissions file

**Comment by xELITESx** [comment]
Im using now MultiWorld, is working fine now.
```
Groups:
  OWNER:
    Permission: nte.owner
    Prefix: '&4[OWNER] '
    Suffix: '&f'
    SortPriority: 1
  ADMIN:
    Permission: nte.admin
    Prefix: '&6[ADMIN] '
    Suffix: '&f'
    SortPriority: 2
  MOD:
    Permission: nte.mod
    Prefix: '&c[MOD] '
    Suffix: '&f'
    SortPriority: 3
  DEVELOPER:
    Permission: nte.dev
    Prefix: '&9[DEVELOPER] '
    Suffix: '&f'
    SortPriority: 4
  HELPER:
    Permission: nte.helper
    Prefix: '&3[HELPER] '
    Suffix: '&f'
    SortPriority: 5
  BUILDER:
    Permission: nte.builder
    Prefix: '&1[BUILDER] '
    Suffix: '&f'
    SortPriority: 6
  MChosting:
    Permission: nte.mc
    Prefix: '&2[MC&fhosting] '
    Suffix: '&f'
    SortPriority: 7
  YouTuber:
    Permission: nte.yt
    Prefix: '&4[Y&fT&4] '
    Suffix: '&f'
    SortPriority: 8
  MiniYT:
    Permission: nte.myt
    Prefix: '&4[MiniYT] '
    Suffix: '&f'
    SortPriority: 9
  ULTRA:
    Permission: nte.ultra
    Prefix: '&6[ULTRA] '
    Suffix: '&f'
    SortPriority: 10
  EPIC:
    Permission: nte.epic
    Prefix: '&e[EPIC] '
    Suffix: '&f'
    SortPriority: 11
  PLUS:
    Permission: nte.plus
    Prefix: '&a[PLUS] '
    Suffix: '&f'
    SortPriority: 12
  VIP:
    Permission: nte.vip
    Prefix: '&b[VIP] '
    Suffix: '&f'
    SortPriority: 13
  Jugador:
    Permission: nte.jugador
    Prefix: '&7[Jugador] '
    Suffix: '&f'
    SortPriority: 14
```
