### ISSUE TITLE
Separation of prefixes in a tab and a head

### ISSUE THREAD

**Issue by DarkFort** [sgtcaze/NametagEdit#230]
With the introduction of longtag, large prefixes are not displayed completely overhead. I suggest adding the second parameter to the config for setting the prefix over the head.

**Comment by sgtcaze** [comment]
So you think there should be a prefix above the head, and a prefix infront of your name in tab (both could be different)? I had this thought as well. I might add a TabFormat option so it looks like:

```
  Admin:
    Permission: nte.admin
    Prefix: '&c'
    Suffix: '&f'
    SortPriority: 1
    TabFormat: '&bSomePrefix &e%player%'
```

Thoughts?
