### ISSUE TITLE
Feature Request - Vanish nametags

### ISSUE THREAD

**Issue by Qw4rtz** [sgtcaze/NametagEdit#27]
Hi,

can you please add custom prefix for vanished players & for each ranks, with full support for VanishNoPacket (available here: http://dev.bukkit.org/bukkit-plugins/vanish/) ?

It would look like:

```
Groups:
  a:
    Permission: nte.a.both # Still customizable, this will allow both default & vanish nametags
    Default:
      Permission: nte.a.default # This will allow default nametag
      Prefix: '&4a &8| &f'
      Suffix: ''
    Vanish:
      Permission: nte.a.vanish # This will allow vanish nametag
      Prefix: '&4a &8| &f'
      Suffix: ' &8 &aVanish'
```

```
Players:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    Name: PlayerA
    Default:
      Prefix: '&6a &8| &f'
      Suffix: ''
    Vanish:
      Prefix: '&6a &8| &f'
      Suffix: ' &8| &cVanish'
```
