### ISSUE TITLE
NametagEdit is not auto assigning group colors based on player's primary group.

### ISSUE THREAD

**Issue by mibby** [sgtcaze/NametagEdit#314]
NametagEdit v4.3.0 compiled as of commit https://github.com/sgtcaze/NametagEdit/commit/f5c068428b19c333b5e4fe58156a0ef3fcf7b840
LuckPerms v4.3.11 dev 789

@JustOneMoreBlock @sgtcaze I'm migrating from the plugin Colored Tags and noticed that NametagEdit does not assign a group color configured based on the player's current primary group.
https://dev.bukkit.org/projects/colored-tags

This is a stripped down example of how I had colored-tags groups.yml.
```
Guest: '&7'
Member: '&b'
Builder: '&b'
VIP: '&a'
Mod: '&d'
Admin: '&c'
```

This is a stripped down example of how I have NametagEdit's groups.yml.

```
Groups:
  Admin:
    Prefix: '&c'
    Suffix: '&f'
  Mod:
    Prefix: '&d'
    Suffix: '&f'
  VIP:
    Prefix: '&a'
    Suffix: '&f'
  Builder:
    Prefix: '&b'
    Suffix: '&f'
  Member:
    Prefix: '&b'
    Suffix: '&f'
  Guest:
    Prefix: '&7'
    Suffix: '&f'
```

With Colored Tags, players automatically got a nametag color assigned to them based on their primary group used. If they switched their primary group (the one used for displaying in-game) to something else, they got the new group tag when they relogged. i.e. blue for builder, green for VIP.

With NameTagEdit, nothing is assigned to the player automatically whatsoever. Would it be possible to hook into LuckPerms and use the configured group prefix based on their primary group?
