### ISSUE TITLE
Can you please add that?

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#324]
#Feature request
Can you please add chat support? For prefixes in the chat That would be great! And please add a config entry to toggle the feature!
Sorry for my bad englisch!

**Comment by JustOneMoreBlock** [comment]
We use to have chat support. However, we removed it. But, this can actually still be accomplished through using Vault, DeluxeChat, and PlaceHolderAPI. This also depends on your permission plugin, I use zPermissions.

Download
https://dev.bukkit.org/projects/vault
https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/

In the NametagEdit Configuration, you would set up `%vault_prefix%` on all the ranks.
https://i.imgur.com/OHKNuL4.png

https://www.spigotmc.org/resources/deluxechat.1277/
```
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '%vault_prefix%'
    name_color: '&f'
    name: '%player_name%'
    suffix: ' &e> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '&3&lName &e&l>&r %player_name%'
    - '&3&lRank &e&l>&r %vault_prefix%'
    name_tooltip:
    - '&3&lMoney &e&l>&r %mvdw_money_rounded%'
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player_name% '
    suffix_click_command: ''
```
_Don't forget the pemission node `chatformat.default`_

Download PlaceHolderAPI:
https://www.spigotmc.org/resources/placeholderapi.6245/

Once loaded you need to run the following commands:
```
/papi elcloud download vault
/papi ecloud download player
/papi ecloud download mvdw
```
_Restart your server. Do not `/reload`_

Now your wondering where do the ranks come from? That's in the permissions plugin I use, I'm sure all permission plugins support this:
```
/perm group NAME create
perm group OWNER prefix '&4&lOWNER &r'
```

The %vault_prefix% can be used anywhere that PlaceHolderAPI or mvdw supports. Example, FeatherBoard, and tab-based plugins.
