### ISSUE TITLE
Group priority not working

### ISSUE THREAD

**Issue by TheBrambleShark** [sgtcaze/NametagEdit#334]
# Bug Report

**Type /ver NametagEdit and post the output.**
Version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Spigot-573cdf2-bd36e20 (1.13.2-R0.1-Snapshot)

**What plugins are you using? Type /plugins**
N/A

**Please explain your issue. How do you trigger it?**
I have the following setup:
**NametagEdit**
```yaml
Groups:
  Default:
    Permission: nte.default
    Prefix: '%vault_suffix%('
    Suffix: ) %vault_prefix%&f%player_displayname%
    SortPriority: 2
  Afk:
    Permission: nte.afk
    Prefix: '&o&7[AFK]%vault_prefix%('
    Suffix: ) %vault_prefix&f%player_displayname%
    SortPriority: 1
```

**LuckPerms:**
1. Default group has `nte.default`
2. Afk group has `nte.afk`

**LFUtils (original plugin)**
1. Hooks Essentials `AfkStatusChangeEvent`
2. OnAfk, adds user group parent of LuckPerms group afk
3. Reloads nametag for that user

As you can see here, the plugin does work, as far as adding a the afk group to the user:
![image](https://user-images.githubusercontent.com/7003081/51082109-1600d600-16c6-11e9-874c-22e68844a470.png)

Additionally, the group does indeed have the correct permission:
![image](https://user-images.githubusercontent.com/7003081/51082119-447eb100-16c6-11e9-8354-12c8350f9d39.png)

**Expected result**
After adding the user to the afk LuckPerms group and refreshing that user through the NTE API, the user should adopt the configuration for the nte.afk group.

I have tested this functionality without my plugin being involved, manually adding users to the LuckPerms afk group and running `/nte reload`. I experience the same result.

**Actual result**
After adding the user to the afk LuckPerms group and refreshing that user through the NTE API, the user remains with the default group.

This behavior is also seen when adding the afk LuckPerms group to the user manually and running `/nte reload`.

**The question**
Is there an issue with my NTE configuration? We're not using any user configurations, and the players.yml file only has the default entries (for sgtcaze and Cory). I have based my configuration off of the way the example is set up on the Wiki, the one with the owner and admin groups. The order of the entries is because of the order in which they were built, using the in-game commands. Further editing was performed by me using nano.

Also, I've noticed that running `/nte reload` likes to remove the quotes around the suffix lines. Adding them back in and running `/nte reload` puts them back, but subsequent reloads removes them again. This does not seem to have any adverse effect on functionality.

**Are there any errors in the console? Please use: https://pastebin.com**
No
