### ISSUE TITLE
Nametag Prefix cut off

### ISSUE THREAD

**Issue by mccormack-harry** [sgtcaze/NametagEdit#569]
# Bug Report

Version: 4.4.10

Server: Paper-288 (1.16.4)

Plugins: There are no other plugin which change player tags that might interfere.

Issue:
![image](https://user-images.githubusercontent.com/14370347/106659470-b02a6400-6596-11eb-80f6-9ce7d5388236.png)
![image](https://user-images.githubusercontent.com/14370347/106660894-7a867a80-6598-11eb-829e-431ce93a44ab.png)
Prefixes are cut off, can't find a reason for it. 

It displays fine on tablist:
![image](https://user-images.githubusercontent.com/14370347/106659833-2929bb80-6597-11eb-81fa-cae6ac8730c3.png)

```
  Staff:
    Permission: nte.staff
    Prefix: '%luckperms_prefix_element_highest_on_track_staff%&f'
    SortPriority: 2
  Donator:
    Permission: nte.donator
    Prefix: '%ranks_prefix% %luckperms_prefix_element_highest_on_track_donator%&f'
    SortPriority: 10
```
```
Tablist:
  # If Enabled, NametagEdit will format the Tab menu
  Enabled: true
  # !! EXPERIMENTAL !!
  # This feature will use the PlayerListName to set your
  # nametag. It will allow you to bypass the 16 character limit
  # for prefix/suffix. Be warned: This does not work on earlier versions
  # of Minecraft. Please report issues to our GitHub, and we'll try to help.
  LongTags: true
```

It happens with all players with a fairly long prefix.

No console errors
