### ISSUE TITLE
Hex Color Codes Capitalization Issue

### ISSUE THREAD

**Issue by accLarson** [sgtcaze/NametagEdit#689]
# Bug Report

ype /ver NametagEdit and post the output.
`version 4.5.4`

What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
`git-paper-81 (mc:1.18.1)`

What plugins are you using? Type /plugins
`Plugins (5): LuckPerms, NametagEdit, PlaceholderAPI, ProtocolLib, Vault`

**Please explain your issue. How do you trigger it?**

When using Hex Colors in groups.yml, capitalization has some strange effect on the functionality of the nametag. For example:
```
Groups:
  administrator:
    Permission: nte.administrator
    Prefix: '&#F2727E TEST'
    Suffix: '&f'
    SortPriority: 1
```
[NameTag Result](https://i.imgur.com/N3N3YfC.png)
[TabMenu Result](https://i.imgur.com/xBi4rlI.png)

while
```
Groups:
  administrator:
    Permission: nte.administrator
    Prefix: '&#f2727e TEST'
    Suffix: '&f'
    SortPriority: 1
```
*note the lowercase letters in the prefix hex color code*
[NameTag Result](https://i.imgur.com/ppZ7gQ9.png) *note the yellow username is another issue I submitted - https://github.com/sgtcaze/NametagEdit/issues/688*
[TabMenu Result](https://i.imgur.com/exi8z6S.png)

**Are there any errors in the console? Please use: https://pastebin.com**
no
